<?php

$finder = Symfony\CS\Finder::create()
    ->in(__DIR__ . '/src')
    ->in(__DIR__ . '/tests');

return Symfony\CS\Config::create()
    ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
    ->fixers([
        // Symfony level fixers
        'array_element_no_space_before_comma',
        'array_element_white_space_after_comma',
        'blankline_after_open_tag',
        // 'concat_without_spaces',
        'declare_equal_normalize',
        'double_arrow_multiline_whitespaces',
        'duplicate_semicolon',
        'extra_empty_lines',
        'function_typehint_space',
        'hash_to_slash_comment',
        'heredoc_to_nowdoc',
        'include',
        'join_function',
        'list_commas',
        'lowercase_cast',
        'method_argument_default_value',
        'multiline_array_trailing_comma',
        'namespace_no_leading_whitespace',
        'native_function_casing',
        'new_with_braces',
        'no_blank_lines_after_class_opening',
        'no_empty_comment',
        'no_empty_lines_after_phpdocs',
        'no_empty_phpdoc',
        'no_empty_statement',
        'object_operator',
        'operators_spaces',
        'php_unit_fqcn_annotation',
        'phpdoc_annotation_without_dot',
        'phpdoc_indent',
        'phpdoc_inline_tag',
        'phpdoc_no_access',
        // 'phpdoc_no_empty_return',
        'phpdoc_no_package',
        // 'phpdoc_params',
        'phpdoc_scalar',
        // 'phpdoc_separation',
        'phpdoc_short_description',
        'phpdoc_single_line_var_spacing',
        'phpdoc_to_comment',
        'phpdoc_trim',
        'phpdoc_type_to_var',
        'phpdoc_types',
        'phpdoc_var_without_name',
        // 'pre_increment',
        'print_to_echo',
        'remove_leading_slash_use',
        'remove_lines_between_uses',
        // 'return',
        'self_accessor',
        'short_bool_cast',
        'short_scalar_cast',
        'single_array_no_trailing_comma',
        'single_blank_line_before_namespace',
        'single_quote',
        'spaces_after_semicolon',
        'spaces_before_semicolon',
        'spaces_cast',
        'standardize_not_equal',
        'ternary_spaces',
        'trim_array_spaces',
        // 'unalign_double_arrow',
        'unalign_equals',
        // 'unary_operators_spaces',
        'unneeded_control_parentheses',
        'unused_use',
        'whitespacy_lines',

        // Contrib level fixers
        // 'align_double_arrow',
        // 'align_equals',
        // 'class_keyword_remove',
        'combine_consecutive_unsets',
        'concat_with_spaces',
        // 'echo_to_print',
        // 'empty_return',
        'ereg_to_preg',
        // 'header_comment',
        // 'logical_not_operators_with_spaces',
        // 'logical_not_operators_with_successor_space',
        // 'long_array_syntax',
        // 'mb_str_functions',
        'multiline_spaces_before_semicolon',
        // 'newline_after_open_tag',
        // 'no_blank_lines_before_namespace',
        'no_useless_else',
        'no_useless_return',
        'ordered_use',
        'php4_constructor',
        'php_unit_construct',
        'php_unit_dedicate_assert',
        'php_unit_strict',
        // 'phpdoc_order',
        // 'phpdoc_var_to_type',
        // 'protected_to_private',
        'short_array_syntax',
        'short_echo_tag',
        // 'silenced_deprecation_error',
        'strict',
        'strict_param',
    ])
    ->finder($finder);
